### ISSUE TITLE
可以把IsQiniuCallback加上吗？

### ISSUE THREAD

**Issue by williambao** [qiniu/api.v6#124]
可事在SDK中增加表单上传的“ IsQiniuCallback”验证方法呢？ 
网站给了一个PHP版的， 但是golang和PHP有不小的差别， 
一般用户到SDK的用户可能会用到IsQiniuCallback。

或者给个golang版的代码也行。 
自己写了个， 但是老是通过不了:(

**Comment by longbai** [comment]
好的

**Comment by xuzhaokui** [comment]
@longbai https://github.com/qiniu/api.v6/pull/133
